using System.Globalization;
using System.Linq;
using System.Text.Json;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ZykeMark.Core.Models;

namespace ZykeMark.Infrastructure.Reporting;

public sealed class ReportGenerator
{
    private readonly BrandTheme _theme;
    private const float SectionGap = 6;
    private const float ItemGap = 2;
    private const float SectionTitleSize = 13;
    private const int MaxWorstFrames = 20;
    private const int MaxWarnings = 10;
    private const int MaxChecklistItems = 10;
    private const int MaxDetailsBullets = 12;

    public ReportGenerator(BrandTheme theme)
    {
        _theme = theme ?? throw new ArgumentNullException(nameof(theme));
    }

    public string Generate(string sessionFolderPath, string? outputPdfPath = null)
    {
        if (string.IsNullOrWhiteSpace(sessionFolderPath))
        {
            throw new ArgumentException("Session folder path is required.", nameof(sessionFolderPath));
        }

        var summaryPath = Path.Combine(sessionFolderPath, "summary.json");
        if (!File.Exists(summaryPath))
        {
            throw new FileNotFoundException("summary.json not found in session folder.", summaryPath);
        }

        var reportData = LoadReportData(summaryPath, Path.Combine(sessionFolderPath, "chunks"));
        var insights = BuildInsights(reportData);
        var outputPath = outputPdfPath ?? Path.Combine(sessionFolderPath, "report.pdf");

        QuestPDF.Settings.License = LicenseType.Community;

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(26);
                page.DefaultTextStyle(text => text.FontFamily("Segoe UI").FontSize(10.5f).FontColor(_theme.Text));
                page.PageColor(_theme.Background);

                page.Header().Column(header =>
                {
                    header.Item().ShowOnce().Element(content => BuildHeader(content, reportData));
                    header.Item().SkipOnce().Element(content => BuildContinuationHeader(content, reportData));
                });
                page.Content().Element(content => BuildContent(content, reportData, insights));
                page.Footer().AlignCenter().Text($"Generated by ZykeMark {reportData.BuildVersion ?? string.Empty}".Trim());
            });
        }).GeneratePdf(outputPath);

        return outputPath;
    }

    public static string FindBrandTokensPath(string? startDirectory = null)
    {
        var current = new DirectoryInfo(startDirectory ?? AppContext.BaseDirectory);

        for (var i = 0; i < 8 && current is not null; i++)
        {
            var candidate = Path.Combine(current.FullName, "src", "ZykeMark.Core", "Brand", "brand.tokens.json");
            if (File.Exists(candidate))
            {
                return candidate;
            }

            var directCandidate = Path.Combine(current.FullName, "brand.tokens.json");
            if (File.Exists(directCandidate))
            {
                return directCandidate;
            }

            current = current.Parent;
        }

        throw new FileNotFoundException("Brand tokens file not found. Expected brand.tokens.json in repository.");
    }

    private static ReportData LoadReportData(string summaryPath, string chunksFolder)
    {
        using var summaryStream = File.OpenRead(summaryPath);
        using var document = JsonDocument.Parse(summaryStream);
        var root = document.RootElement;

        var metadata = root.GetProperty("metadata");
        var aggregates = root.GetProperty("aggregates");

        var sessionId = metadata.GetProperty("SessionId").GetString() ?? "Unknown";
        var startedAtUtc = TryReadUtcTimestamp(metadata, "StartedAtUtc", out var startedTimestamp)
            ? startedTimestamp
            : (DateTime?)null;
        var endedAtUtc = TryReadUtcTimestamp(metadata, "EndedAtUtc", out var endedTimestamp)
            ? endedTimestamp
            : (DateTime?)null;

        var durationMs = metadata.GetProperty("DurationMs").ValueKind == JsonValueKind.Null
            ? (long?)null
            : ReadLongMs(metadata.GetProperty("DurationMs"), "metadata.DurationMs");

        var gameName = metadata.TryGetProperty("GameName", out var gameProp) ? gameProp.GetString() : null;
        var buildVersion = metadata.TryGetProperty("BuildVersion", out var buildProp) ? buildProp.GetString() : null;
        var captureTarget = metadata.TryGetProperty("CaptureTarget", out var captureTargetProp)
            ? captureTargetProp.GetString()
            : null;
        var captureMode = metadata.TryGetProperty("CaptureMode", out var captureModeProp)
            ? captureModeProp.GetString()
            : null;
        var presentMonVersion = metadata.TryGetProperty("PresentMonVersion", out var presentMonProp)
            ? presentMonProp.GetString()
            : null;

        var runConfig = metadata.TryGetProperty("RunConfig", out var runConfigProp)
            ? ParseRunConfig(runConfigProp)
            : new RunConfig();

        var aggregatesDurationMs = aggregates.TryGetProperty("DurationMs", out var durationProp)
            && durationProp.ValueKind != JsonValueKind.Null
            ? ReadLongMs(durationProp, "aggregates.DurationMs")
            : 0L;
        var avgFps = ReadDoubleMs(aggregates.GetProperty("AvgFps"), "aggregates.AvgFps");
        var onePercentLow = ReadDoubleMs(aggregates.GetProperty("OnePercentLowFps"), "aggregates.OnePercentLowFps");
        var pointOnePercentLow = ReadDoubleMs(aggregates.GetProperty("PointOnePercentLowFps"), "aggregates.PointOnePercentLowFps");
        var avgFrameTimeMs = ReadDoubleMs(aggregates.GetProperty("AvgFrameTimeMs"), "aggregates.AvgFrameTimeMs");
        var p99FrameTimeMs = ReadDoubleMs(aggregates.GetProperty("P99FrameTimeMs"), "aggregates.P99FrameTimeMs");
        var frameCount = aggregates.GetProperty("FrameCount").GetInt32();

        var avgCpuFrameTimeMs = aggregates.TryGetProperty("AvgCpuFrameTimeMs", out var cpuProp)
            && cpuProp.ValueKind != JsonValueKind.Null
            ? ReadDoubleMs(cpuProp, "aggregates.AvgCpuFrameTimeMs")
            : (double?)null;

        var avgGpuFrameTimeMs = aggregates.TryGetProperty("AvgGpuFrameTimeMs", out var gpuProp)
            && gpuProp.ValueKind != JsonValueKind.Null
            ? ReadDoubleMs(gpuProp, "aggregates.AvgGpuFrameTimeMs")
            : (double?)null;

        var chunkStats = File.Exists(chunksFolder) || Directory.Exists(chunksFolder)
            ? ComputeChunkStats(chunksFolder)
            : ChunkStats.Empty;

        var effectiveDurationMs = ResolveEffectiveDurationMs(aggregatesDurationMs, durationMs, startedAtUtc, endedAtUtc);

        return new ReportData(
            sessionId,
            startedAtUtc,
            endedAtUtc,
            durationMs,
            effectiveDurationMs,
            gameName,
            buildVersion,
            captureTarget,
            captureMode,
            presentMonVersion,
            runConfig,
            avgFps,
            onePercentLow,
            pointOnePercentLow,
            avgFrameTimeMs,
            p99FrameTimeMs,
            frameCount,
            avgCpuFrameTimeMs,
            avgGpuFrameTimeMs,
            chunkStats);
    }

    private static RunConfig ParseRunConfig(JsonElement runConfigProp)
    {
        if (runConfigProp.ValueKind == JsonValueKind.Null)
        {
            return new RunConfig();
        }

        var api = runConfigProp.TryGetProperty("Api", out var apiProp) ? apiProp.GetString() : null;
        var resolution = runConfigProp.TryGetProperty("Resolution", out var resProp) ? resProp.GetString() : null;
        var preset = runConfigProp.TryGetProperty("Preset", out var presetProp) ? presetProp.GetString() : null;

        return new RunConfig(api, resolution, preset);
    }

    private static ChunkStats ComputeChunkStats(string chunksFolder)
    {
        if (!Directory.Exists(chunksFolder))
        {
            return ChunkStats.Empty;
        }

        var files = Directory.GetFiles(chunksFolder, "chunk_*.json");
        if (files.Length == 0)
        {
            return ChunkStats.Empty;
        }

        var stutter50 = 0;
        var stutter100 = 0;
        double worstFrameTime = 0;
        var worstFrames = new List<double>(MaxWorstFrames);

        foreach (var file in files)
        {
            using var stream = File.OpenRead(file);
            var chunk = JsonSerializer.Deserialize<RawSampleChunk>(stream);
            if (chunk?.Samples is null)
            {
                continue;
            }

            foreach (var sample in chunk.Samples)
            {
                if (sample.FrameTimeMs >= 50)
                {
                    stutter50++;
                }

                if (sample.FrameTimeMs >= 100)
                {
                    stutter100++;
                }

                if (sample.FrameTimeMs > worstFrameTime)
                {
                    worstFrameTime = sample.FrameTimeMs;
                }

                TrackWorstFrame(worstFrames, sample.FrameTimeMs);
            }
        }

        worstFrames.Sort((left, right) => right.CompareTo(left));
        return new ChunkStats(stutter50, stutter100, worstFrameTime, worstFrames);
    }

    private void BuildHeader(IContainer container, ReportData data)
    {
        container.Background(_theme.Primary).Padding(12).Row(row =>
        {
            row.RelativeItem().Column(column =>
            {
                column.Item().Text("ZykeMark Performance Report").FontSize(18).SemiBold();
                column.Item().Text($"Session: {data.SessionId}").FontSize(10);
                column.Item().Text($"Started: {FormatTimestamp(data.StartedAtUtc) ?? "Not provided"}").FontSize(10);
                column.Item().Text($"Ended: {FormatTimestamp(data.EndedAtUtc) ?? "Not ended"}").FontSize(10);
            });

            row.ConstantItem(200).Column(column =>
            {
                if (!string.IsNullOrWhiteSpace(data.GameName))
                {
                    column.Item().AlignRight().Text(data.GameName).SemiBold();
                }

                if (!string.IsNullOrWhiteSpace(data.BuildVersion))
                {
                    column.Item().AlignRight().Text($"Build: {data.BuildVersion}");
                }
            });
        });
    }

    private void BuildContinuationHeader(IContainer container, ReportData data)
    {
        container.BorderBottom(1).BorderColor(_theme.Primary).Padding(6).Row(row =>
        {
            row.RelativeItem().Text("ZykeMark Performance Report").FontSize(12).SemiBold().FontColor(_theme.Primary);
            row.ConstantItem(200).AlignRight().Text(data.GameName ?? "Not provided").FontSize(10);
        });
    }

    private void BuildContent(IContainer container, ReportData data, ReportInsights insights)
    {
        var verdict = BuildVerdict(data, insights);
        var nextRunItems = BuildNextRunItems(data, insights);

        container.PaddingVertical(10).Column(column =>
        {
            column.Spacing(SectionGap);
            column.Item().Element(section => BuildCaptureDetails(section, data));
            column.Item().Element(section => BuildVerdict(section, verdict));
            column.Item().EnsureSpace(80).ShowEntire().Element(section => BuildNextSteps(section, data, nextRunItems));
            column.Item().Element(section => BuildRunConfig(section, data));
            column.Item().Element(section => BuildKeyMetrics(section, data));
            column.Item().Element(section => BuildCpuGpu(section, data));
            column.Item().Element(section => BuildStability(section, data));
            column.Item().ShowEntire().Element(section => BuildDataQuality(section, data, insights));
            column.Item().Element(section => BuildInterpretationNotes(section, insights));
            if (verdict.IncludeDetailsPage)
            {
                column.Item().PageBreak();
                column.Item().Element(section => BuildDetailsPage(section, data));
            }
        });
    }

    private void BuildCaptureDetails(IContainer container, ReportData data)
    {
        container.Column(column =>
        {
            column.Spacing(ItemGap);
            column.Item().Text("Capture Details").FontSize(SectionTitleSize).FontColor(_theme.Primary).SemiBold();
            var details = new List<string>();
            if (!string.IsNullOrWhiteSpace(data.CaptureTarget)) details.Add($"Target: {data.CaptureTarget}");
            if (!string.IsNullOrWhiteSpace(data.CaptureMode)) details.Add($"Mode: {data.CaptureMode}");
            if (!string.IsNullOrWhiteSpace(data.PresentMonVersion)) details.Add($"PresentMon: {data.PresentMonVersion}");
            details.Add($"Samples: {data.FrameCount.ToString("N0", CultureInfo.InvariantCulture)}");
            column.Item().Text(string.Join(" | ", details));
        });
    }

    private void BuildVerdict(IContainer container, Verdict verdict)
    {
        container.Column(column =>
        {
            column.Spacing(ItemGap);
            column.Item().Text("Verdict / Summary").FontSize(SectionTitleSize).FontColor(_theme.Primary).SemiBold();
            column.Item().Row(row =>
            {
                row.Spacing(6);
                row.RelativeItem().Element(card => BuildVerdictChip(card, "Bound", verdict.Bound));
                row.RelativeItem().Element(card => BuildVerdictChip(card, "Stability", verdict.Stability));
                row.RelativeItem().Element(card => BuildVerdictChip(card, "Confidence", verdict.Confidence));
            });
        });
    }

    private void BuildRunConfig(IContainer container, ReportData data)
    {
        container.Column(column =>
        {
            column.Spacing(ItemGap);
            column.Item().Text("System & Run Config").FontSize(SectionTitleSize).FontColor(_theme.Primary).SemiBold();
            if (!string.IsNullOrWhiteSpace(data.RunConfig.Api))
            {
                column.Item().Text($"API: {data.RunConfig.Api}");
            }
            if (!string.IsNullOrWhiteSpace(data.RunConfig.Resolution))
            {
                column.Item().Text($"Resolution: {data.RunConfig.Resolution}");
            }
            if (!string.IsNullOrWhiteSpace(data.RunConfig.Preset))
            {
                column.Item().Text($"Preset: {data.RunConfig.Preset}");
            }
            if (string.IsNullOrWhiteSpace(data.RunConfig.Api)
                && string.IsNullOrWhiteSpace(data.RunConfig.Resolution)
                && string.IsNullOrWhiteSpace(data.RunConfig.Preset))
            {
                column.Item().Text("No run config provided.");
            }

            var warnings = new List<string>();
            if (string.IsNullOrWhiteSpace(data.GameName)) warnings.Add("GameName");
            if (string.IsNullOrWhiteSpace(data.BuildVersion)) warnings.Add("BuildVersion");
            if (string.IsNullOrWhiteSpace(data.RunConfig.Api)) warnings.Add("API");
            if (string.IsNullOrWhiteSpace(data.RunConfig.Resolution)) warnings.Add("Resolution");
            if (string.IsNullOrWhiteSpace(data.RunConfig.Preset)) warnings.Add("Preset");

            if (warnings.Count > 0)
            {
                column.Item().PaddingTop(ItemGap).Row(row =>
                {
                    row.ConstantItem(70).Element(badge => BuildSeverityBadge(badge, "Info", Severity.Info));
                    row.RelativeItem().Text($"Missing: {string.Join(", ", warnings)}.");
                });
            }
        });
    }

    private void BuildKeyMetrics(IContainer container, ReportData data)
    {
        container.Column(column =>
        {
            column.Item().Text("Key Performance Metrics").FontSize(SectionTitleSize).FontColor(_theme.Primary).SemiBold();
            column.Item().PaddingTop(ItemGap).Column(grid =>
            {
                grid.Spacing(ItemGap);
                grid.Item().Row(row =>
                {
                    row.Spacing(ItemGap);
                    row.RelativeItem().Element(card => BuildMetricCard(card, "Avg FPS", data.AvgFps.ToString("F1", CultureInfo.InvariantCulture)));
                    row.RelativeItem().Element(card => BuildMetricCard(card, "1% Low", data.OnePercentLowFps.ToString("F1", CultureInfo.InvariantCulture)));
                });
                grid.Item().Row(row =>
                {
                    row.Spacing(ItemGap);
                    row.RelativeItem().Element(card => BuildMetricCard(card, "0.1% Low", data.PointOnePercentLowFps.ToString("F1", CultureInfo.InvariantCulture)));
                    row.RelativeItem().Element(card => BuildMetricCard(card, "P99 Frame Time (ms)", data.P99FrameTimeMs.ToString("F2", CultureInfo.InvariantCulture)));
                });
                grid.Item().Row(row =>
                {
                    row.Spacing(ItemGap);
                    row.RelativeItem().Element(card => BuildMetricCard(card, "Avg Frame Time (ms)", data.AvgFrameTimeMs.ToString("F2", CultureInfo.InvariantCulture)));
                    row.RelativeItem().Element(card => BuildMetricCard(card, "Duration", FormatDuration(data.EffectiveDurationMs)));
                });
            });
        });
    }

    private void BuildCpuGpu(IContainer container, ReportData data)
    {
        container.Column(column =>
        {
            column.Spacing(ItemGap);
            column.Item().Text("CPU vs GPU Balance").FontSize(SectionTitleSize).FontColor(_theme.Primary).SemiBold();
            column.Item().Text($"Avg CPU Frame Time: {FormatNullableMs(data.AvgCpuFrameTimeMs)}");
            column.Item().Text($"Avg GPU Frame Time: {FormatNullableMs(data.AvgGpuFrameTimeMs)}");
            column.Item().Text($"Balance Hint: {GetBalanceHint(data.AvgCpuFrameTimeMs, data.AvgGpuFrameTimeMs)}");
        });
    }

    private void BuildStability(IContainer container, ReportData data)
    {
        container.Column(column =>
        {
            column.Spacing(ItemGap);
            column.Item().Text("Stability / Stutter").FontSize(SectionTitleSize).FontColor(_theme.Primary).SemiBold();
            column.Item().Text($"P99 Frame Time: {data.P99FrameTimeMs.ToString("F2", CultureInfo.InvariantCulture)} ms");
            if (data.ChunkStats.HasData)
            {
                column.Item().Text($"Worst Frame Time: {data.ChunkStats.WorstFrameTimeMs.ToString("F2", CultureInfo.InvariantCulture)} ms");
                column.Item().Text($"Stutter Events >= 50ms: {data.ChunkStats.StutterEvents50Ms}");
                column.Item().Text($"Stutter Events >= 100ms: {data.ChunkStats.StutterEvents100Ms}");
            }
            else
            {
                column.Item().Text("No chunk data available for stutter analysis.");
            }
        });
    }

    private void BuildDataQuality(IContainer container, ReportData data, ReportInsights insights)
    {
        container.Column(column =>
        {
            column.Spacing(ItemGap);
            column.Item().Text("Data Quality & Context").FontSize(SectionTitleSize).FontColor(_theme.Primary).SemiBold();

            if (insights.Flags.Count == 0)
            {
                column.Item().Text("No data-quality warnings detected for this run.");
                return;
            }

            foreach (var flag in insights.Flags.Take(MaxWarnings))
            {
                column.Item().Row(row =>
                {
                    row.ConstantItem(70).Element(badge => BuildSeverityBadge(badge, flag.SeverityLabel, flag.Severity));
                    row.RelativeItem().Text($"{flag.Title}: {flag.Description}");
                });
            }
        });
    }

    private void BuildInterpretationNotes(IContainer container, ReportInsights insights)
    {
        container.Column(column =>
        {
            column.Spacing(ItemGap);
            column.Item().Text("Interpretation Notes").FontSize(SectionTitleSize).FontColor(_theme.Primary).SemiBold();
            var notes = new List<string>
            {
                "1%/0.1% lows can be distorted by focus loss, background activity, or overlays.",
                "Worst-frame spikes should be validated against run conditions before acting."
            };

            if (insights.DesktopCaptureLikely)
            {
                notes.Add("Desktop capture detected. Prefer capturing the actual game process for actionable lows.");
            }

            BuildBulletList(column, notes.Take(3));
        });
    }

    private void BuildNextSteps(IContainer container, ReportData data, IReadOnlyList<string> nextRunItems)
    {
        container.Column(column =>
        {
            column.Spacing(ItemGap);
            column.Item().Text("Next Steps").FontSize(SectionTitleSize).FontColor(_theme.Primary).SemiBold();
            column.Item().Row(row =>
            {
                row.Spacing(10);
                row.RelativeItem().Column(left =>
                {
                    left.Spacing(ItemGap);
                    left.Item().Text("Fix in next run").FontSize(10).FontColor(_theme.Primary).SemiBold();
                    BuildBulletList(left, nextRunItems.Take(MaxChecklistItems));
                });
                row.RelativeItem().Column(right =>
                {
                    right.Spacing(ItemGap);
                    right.Item().Text("Performance actions").FontSize(10).FontColor(_theme.Primary).SemiBold();
                    var hint = GetBalanceHint(data.AvgCpuFrameTimeMs, data.AvgGpuFrameTimeMs);

                    if (hint == "Likely CPU-bound")
                    {
                        BuildBulletList(right, new[]
                        {
                            "Profile main-thread hotspots and reduce simulation cost.",
                            "Reduce draw calls/state changes and improve batching.",
                            "Validate background tasks and thread contention."
                        });
                    }
                    else if (hint == "Likely GPU-bound")
                    {
                        BuildBulletList(right, new[]
                        {
                            "Review shader complexity and post-processing passes.",
                            "Evaluate resolution scaling or dynamic quality settings.",
                            "Optimize texture/RT budget and overdraw."
                        });
                    }
                    else
                    {
                        BuildBulletList(right, new[]
                        {
                            "Capture a longer run to reduce variance.",
                            "Ensure fixed settings and consistent scene context."
                        });
                    }
                });
            });
        });
    }

    private void BuildDetailsPage(IContainer container, ReportData data)
    {
        container.Column(column =>
        {
            column.Spacing(ItemGap);
            column.Item().Text("Details").FontSize(SectionTitleSize).FontColor(_theme.Primary).SemiBold();
            column.Item().Text("Extended interpretation and stability context for longer runs:");
            BuildBulletList(column, new[]
                {
                    $"Frame count: {data.FrameCount.ToString("N0", CultureInfo.InvariantCulture)}",
                    $"P99 frame time: {data.P99FrameTimeMs.ToString("F2", CultureInfo.InvariantCulture)} ms",
                    $"Worst frame time: {data.ChunkStats.WorstFrameTimeMs.ToString("F2", CultureInfo.InvariantCulture)} ms",
                    $"Stutter >= 50ms: {data.ChunkStats.StutterEvents50Ms}",
                    $"Stutter >= 100ms: {data.ChunkStats.StutterEvents100Ms}"
                }
                .Take(MaxDetailsBullets));

            if (data.ChunkStats.WorstFrameTimes.Count > 0)
            {
                column.Item().PaddingTop(ItemGap).Text("Worst frames (top)").FontSize(10).FontColor(_theme.Primary).SemiBold();
                BuildBulletList(column, data.ChunkStats.WorstFrameTimes
                    .Select(value => $"{value.ToString("F2", CultureInfo.InvariantCulture)} ms")
                    .Take(MaxWorstFrames));
            }

            column.Item().PaddingTop(ItemGap).Text("Notes").FontSize(10).FontColor(_theme.Primary).SemiBold();
            BuildBulletList(column, new[]
                {
                    "Use comparable settings for meaningful trend lines.",
                    "Capture longer runs when investigating intermittent spikes."
                }
                .Take(MaxDetailsBullets));
        });
    }

    private static string ValueOrNotProvided(string? value) => string.IsNullOrWhiteSpace(value) ? "Not provided" : value;

    private static string FormatDuration(long durationMs)
    {
        if (durationMs <= 0)
        {
            return "Not provided";
        }

        var seconds = durationMs / 1000.0;
        return $"{seconds.ToString("F1", CultureInfo.InvariantCulture)} s";
    }

    private static string FormatNullableMs(double? value)
    {
        return value.HasValue
            ? $"{value.Value.ToString("F2", CultureInfo.InvariantCulture)} ms"
            : "Not provided";
    }

    private static string GetBalanceHint(double? cpuMs, double? gpuMs)
    {
        if (!cpuMs.HasValue || !gpuMs.HasValue)
        {
            return "Balanced / unclear";
        }

        if (cpuMs.Value > gpuMs.Value * 1.10)
        {
            return "Likely CPU-bound";
        }

        if (gpuMs.Value > cpuMs.Value * 1.10)
        {
            return "Likely GPU-bound";
        }

        return "Balanced / unclear";
    }

    private void BuildMetricCard(IContainer container, string title, string value)
    {
        container.Border(0.5f).BorderColor(_theme.Primary).Padding(6).Column(column =>
        {
            column.Spacing(ItemGap);
            column.Item().Text(title).FontSize(9.5f).FontColor(_theme.Primary);
            column.Item().Text(value).FontSize(14).SemiBold();
        });
    }

    private void BuildSeverityBadge(IContainer container, string label, Severity severity)
    {
        var color = severity switch
        {
            Severity.High => _theme.Accent,
            Severity.Warning => _theme.Primary,
            Severity.Info => _theme.Primary,
            _ => _theme.Primary
        };

        container.Background(color).PaddingHorizontal(6).PaddingVertical(2)
            .AlignCenter().Text(label).FontSize(9).FontColor(_theme.Text).SemiBold();
    }

    private static void BuildBulletList(ColumnDescriptor column, IEnumerable<string> items)
    {
        foreach (var item in items)
        {
            column.Item().Text($"• {item}");
        }
    }

    private static ReportInsights BuildInsights(ReportData data)
    {
        var flags = new List<InsightFlag>();

        if (data.FrameCount < 300)
        {
            flags.Add(new InsightFlag("Insufficient Sample Size", "Fewer than 300 frames captured; lows may be unstable.", Severity.Warning));
        }

        if (data.ChunkStats.WorstFrameTimeMs >= 1000)
        {
            flags.Add(new InsightFlag("High Outlier Risk", "Worst frame exceeded 1000 ms; verify focus and background load.", Severity.High));
        }

        if (data.ChunkStats.StutterEvents100Ms >= 20 || data.P99FrameTimeMs >= 100)
        {
            flags.Add(new InsightFlag("Severe Stutter", "High stutter frequency or elevated P99 frame time detected.", Severity.High));
        }

        var desktopCaptureLikely = !string.IsNullOrWhiteSpace(data.GameName)
            && data.GameName.Contains("Desktop", StringComparison.OrdinalIgnoreCase);

        if (desktopCaptureLikely)
        {
            flags.Add(new InsightFlag("Desktop Capture Likely", "Game name suggests a desktop capture rather than a game process.", Severity.Info));
        }

        return new ReportInsights(flags, desktopCaptureLikely);
    }

    private Verdict BuildVerdict(ReportData data, ReportInsights insights)
    {
        var boundHint = GetBalanceHint(data.AvgCpuFrameTimeMs, data.AvgGpuFrameTimeMs);
        var bound = boundHint switch
        {
            "Likely CPU-bound" => "CPU-bound",
            "Likely GPU-bound" => "GPU-bound",
            _ => "Unknown"
        };

        var stability = data.P99FrameTimeMs >= 100 || data.ChunkStats.StutterEvents100Ms >= 20
            ? "Severe"
            : data.P99FrameTimeMs >= 50 || data.ChunkStats.StutterEvents50Ms >= 20
                ? "Moderate"
                : "OK";

        var hasAllConfig = !string.IsNullOrWhiteSpace(data.RunConfig.Api)
            && !string.IsNullOrWhiteSpace(data.RunConfig.Resolution)
            && !string.IsNullOrWhiteSpace(data.RunConfig.Preset);

        var confidence = !hasAllConfig || insights.DesktopCaptureLikely
            ? "Low"
            : data.FrameCount < 300
                ? "Medium"
                : "High";

        var includeDetailsPage = data.FrameCount >= 2_000 || data.ChunkStats.StutterEvents100Ms >= 50;

        return new Verdict(bound, stability, confidence, includeDetailsPage);
    }

    private static IReadOnlyList<string> BuildNextRunItems(ReportData data, ReportInsights insights)
    {
        var missing = new List<string>();
        if (string.IsNullOrWhiteSpace(data.RunConfig.Api)) missing.Add("Provide API (e.g., DX12)");
        if (string.IsNullOrWhiteSpace(data.RunConfig.Resolution)) missing.Add("Provide Resolution (e.g., 1920x1080)");
        if (string.IsNullOrWhiteSpace(data.RunConfig.Preset)) missing.Add("Provide Preset (e.g., High)");
        if (insights.DesktopCaptureLikely) missing.Add("Capture the actual game process (not desktop/DWM)");
        if (missing.Count == 0) missing.Add("No metadata fixes required for next run.");
        return missing.Take(MaxChecklistItems).ToArray();
    }

    private void BuildVerdictChip(IContainer container, string label, string value)
    {
        container.Border(0.5f).BorderColor(_theme.Primary).PaddingHorizontal(6).PaddingVertical(4).Row(row =>
        {
            row.RelativeItem().Text($"{label}: {value}").FontSize(10).SemiBold();
        });
    }

    private static void TrackWorstFrame(List<double> worstFrames, double frameTimeMs)
    {
        if (frameTimeMs <= 0)
        {
            return;
        }

        if (worstFrames.Count < MaxWorstFrames)
        {
            worstFrames.Add(frameTimeMs);
            return;
        }

        var minIndex = 0;
        var minValue = worstFrames[0];
        for (var i = 1; i < worstFrames.Count; i++)
        {
            if (worstFrames[i] < minValue)
            {
                minValue = worstFrames[i];
                minIndex = i;
            }
        }

        if (frameTimeMs > minValue)
        {
            worstFrames[minIndex] = frameTimeMs;
        }
    }

    private sealed record ReportData(
        string SessionId,
        DateTime? StartedAtUtc,
        DateTime? EndedAtUtc,
        long? DurationMs,
        long EffectiveDurationMs,
        string? GameName,
        string? BuildVersion,
        string? CaptureTarget,
        string? CaptureMode,
        string? PresentMonVersion,
        RunConfig RunConfig,
        double AvgFps,
        double OnePercentLowFps,
        double PointOnePercentLowFps,
        double AvgFrameTimeMs,
        double P99FrameTimeMs,
        int FrameCount,
        double? AvgCpuFrameTimeMs,
        double? AvgGpuFrameTimeMs,
        ChunkStats ChunkStats);

    private sealed record ChunkStats(
        int StutterEvents50Ms,
        int StutterEvents100Ms,
        double WorstFrameTimeMs,
        IReadOnlyList<double> WorstFrameTimes)
    {
        public static ChunkStats Empty => new(0, 0, 0, Array.Empty<double>());
        public bool HasData => StutterEvents50Ms > 0 || StutterEvents100Ms > 0 || WorstFrameTimeMs > 0;
    }

    private sealed record ReportInsights(IReadOnlyList<InsightFlag> Flags, bool DesktopCaptureLikely);

    private sealed record InsightFlag(string Title, string Description, Severity Severity)
    {
        public string SeverityLabel => Severity switch
        {
            Severity.High => "High",
            Severity.Warning => "Warning",
            Severity.Info => "Info",
            _ => "Info"
        };
    }

    private enum Severity
    {
        Info,
        Warning,
        High
    }

    private sealed record Verdict(string Bound, string Stability, string Confidence, bool IncludeDetailsPage);

    private static long ResolveEffectiveDurationMs(long aggregatesDurationMs, long? metadataDurationMs, DateTime? startedAtUtc, DateTime? endedAtUtc)
    {
        if (aggregatesDurationMs > 0)
        {
            return aggregatesDurationMs;
        }

        if (metadataDurationMs.HasValue && metadataDurationMs.Value > 0)
        {
            return metadataDurationMs.Value;
        }

        if (startedAtUtc.HasValue && endedAtUtc.HasValue && endedAtUtc.Value > startedAtUtc.Value)
        {
            var span = endedAtUtc.Value - startedAtUtc.Value;
            return (long)span.TotalMilliseconds;
        }

        return 0;
    }

    private static bool TryReadUtcTimestamp(JsonElement metadata, string propertyName, out DateTime value)
    {
        value = default;
        if (!metadata.TryGetProperty(propertyName, out var prop) || prop.ValueKind == JsonValueKind.Null)
        {
            return false;
        }

        if (prop.ValueKind == JsonValueKind.String)
        {
            var raw = prop.GetString();
            if (string.IsNullOrWhiteSpace(raw))
            {
                return false;
            }

            if (DateTimeOffset.TryParse(raw, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out var offset))
            {
                value = offset.UtcDateTime;
                return true;
            }

            if (DateTime.TryParse(raw, CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal, out var parsed))
            {
                value = parsed;
                return true;
            }

            return false;
        }

        if (prop.ValueKind == JsonValueKind.Number && prop.TryGetInt64(out var ticks))
        {
            value = new DateTime(ticks, DateTimeKind.Utc);
            return true;
        }

        return false;
    }

    private static string? FormatTimestamp(DateTime? timestamp)
    {
        return timestamp.HasValue ? timestamp.Value.ToUniversalTime().ToString("O", CultureInfo.InvariantCulture) : null;
    }

    private static long ReadLongMs(JsonElement element, string fieldName)
    {
        if (element.ValueKind == JsonValueKind.Number)
        {
            if (element.TryGetInt64(out var value))
            {
                return value;
            }

            if (element.TryGetDouble(out var doubleValue))
            {
                return (long)Math.Round(doubleValue, MidpointRounding.AwayFromZero);
            }
        }

        if (element.ValueKind == JsonValueKind.String)
        {
            var raw = element.GetString();
            if (double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed))
            {
                return (long)Math.Round(parsed, MidpointRounding.AwayFromZero);
            }
        }

        throw new FormatException($"Expected a numeric milliseconds value for {fieldName}.");
    }

    private static double ReadDoubleMs(JsonElement element, string fieldName)
    {
        if (element.ValueKind == JsonValueKind.Number)
        {
            if (element.TryGetDouble(out var value))
            {
                return value;
            }

            if (element.TryGetInt64(out var intValue))
            {
                return intValue;
            }
        }

        if (element.ValueKind == JsonValueKind.String)
        {
            var raw = element.GetString();
            if (double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed))
            {
                return parsed;
            }
        }

        throw new FormatException($"Expected a numeric milliseconds value for {fieldName}.");
    }
}
