using System.Globalization;
using System.Text.Json;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ZykeMark.Core.Models;

namespace ZykeMark.Infrastructure.Reporting;

public sealed class ReportGenerator
{
    private readonly BrandTheme _theme;

    public ReportGenerator(BrandTheme theme)
    {
        _theme = theme ?? throw new ArgumentNullException(nameof(theme));
    }

    public string Generate(string sessionFolderPath, string? outputPdfPath = null)
    {
        if (string.IsNullOrWhiteSpace(sessionFolderPath))
        {
            throw new ArgumentException("Session folder path is required.", nameof(sessionFolderPath));
        }

        var summaryPath = Path.Combine(sessionFolderPath, "summary.json");
        if (!File.Exists(summaryPath))
        {
            throw new FileNotFoundException("summary.json not found in session folder.", summaryPath);
        }

        var reportData = LoadReportData(summaryPath, Path.Combine(sessionFolderPath, "chunks"));
        var insights = BuildInsights(reportData);
        var outputPath = outputPdfPath ?? Path.Combine(sessionFolderPath, "report.pdf");

        QuestPDF.Settings.License = LicenseType.Community;

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(30);
                page.DefaultTextStyle(text => text.FontFamily("Segoe UI").FontSize(11).FontColor(_theme.Text));
                page.PageColor(_theme.Background);

                page.Header().Element(header => BuildHeader(header, reportData));
                page.Content().Element(content => BuildContent(content, reportData, insights));
                page.Footer().AlignCenter().Text($"Generated by ZykeMark {reportData.BuildVersion ?? string.Empty}".Trim());
            });
        }).GeneratePdf(outputPath);

        return outputPath;
    }

    public static string FindBrandTokensPath(string? startDirectory = null)
    {
        var current = new DirectoryInfo(startDirectory ?? AppContext.BaseDirectory);

        for (var i = 0; i < 8 && current is not null; i++)
        {
            var candidate = Path.Combine(current.FullName, "src", "ZykeMark.Core", "Brand", "brand.tokens.json");
            if (File.Exists(candidate))
            {
                return candidate;
            }

            var directCandidate = Path.Combine(current.FullName, "brand.tokens.json");
            if (File.Exists(directCandidate))
            {
                return directCandidate;
            }

            current = current.Parent;
        }

        throw new FileNotFoundException("Brand tokens file not found. Expected brand.tokens.json in repository.");
    }

    private static ReportData LoadReportData(string summaryPath, string chunksFolder)
    {
        using var summaryStream = File.OpenRead(summaryPath);
        using var document = JsonDocument.Parse(summaryStream);
        var root = document.RootElement;

        var metadata = root.GetProperty("metadata");
        var aggregates = root.GetProperty("aggregates");

        var sessionId = metadata.GetProperty("SessionId").GetString() ?? "Unknown";
        var startedAtUtc = metadata.GetProperty("StartedAtUtc").GetDateTime();
        var endedAtUtc = metadata.GetProperty("EndedAtUtc").ValueKind == JsonValueKind.Null
            ? (DateTime?)null
            : metadata.GetProperty("EndedAtUtc").GetDateTime();

        var durationMs = metadata.GetProperty("DurationMs").ValueKind == JsonValueKind.Null
            ? (long?)null
            : metadata.GetProperty("DurationMs").GetInt64();

        var gameName = metadata.TryGetProperty("GameName", out var gameProp) ? gameProp.GetString() : null;
        var buildVersion = metadata.TryGetProperty("BuildVersion", out var buildProp) ? buildProp.GetString() : null;

        var runConfig = metadata.TryGetProperty("RunConfig", out var runConfigProp)
            ? ParseRunConfig(runConfigProp)
            : new RunConfig();

        var avgFps = aggregates.GetProperty("AvgFps").GetDouble();
        var onePercentLow = aggregates.GetProperty("OnePercentLowFps").GetDouble();
        var pointOnePercentLow = aggregates.GetProperty("PointOnePercentLowFps").GetDouble();
        var avgFrameTimeMs = aggregates.GetProperty("AvgFrameTimeMs").GetDouble();
        var p99FrameTimeMs = aggregates.GetProperty("P99FrameTimeMs").GetDouble();
        var frameCount = aggregates.GetProperty("FrameCount").GetInt32();

        var avgCpuFrameTimeMs = aggregates.TryGetProperty("AvgCpuFrameTimeMs", out var cpuProp)
            && cpuProp.ValueKind != JsonValueKind.Null
            ? cpuProp.GetDouble()
            : (double?)null;

        var avgGpuFrameTimeMs = aggregates.TryGetProperty("AvgGpuFrameTimeMs", out var gpuProp)
            && gpuProp.ValueKind != JsonValueKind.Null
            ? gpuProp.GetDouble()
            : (double?)null;

        var chunkStats = File.Exists(chunksFolder) || Directory.Exists(chunksFolder)
            ? ComputeChunkStats(chunksFolder)
            : ChunkStats.Empty;

        return new ReportData(
            sessionId,
            startedAtUtc,
            endedAtUtc,
            durationMs,
            gameName,
            buildVersion,
            runConfig,
            avgFps,
            onePercentLow,
            pointOnePercentLow,
            avgFrameTimeMs,
            p99FrameTimeMs,
            frameCount,
            avgCpuFrameTimeMs,
            avgGpuFrameTimeMs,
            chunkStats);
    }

    private static RunConfig ParseRunConfig(JsonElement runConfigProp)
    {
        if (runConfigProp.ValueKind == JsonValueKind.Null)
        {
            return new RunConfig();
        }

        var api = runConfigProp.TryGetProperty("Api", out var apiProp) ? apiProp.GetString() : null;
        var resolution = runConfigProp.TryGetProperty("Resolution", out var resProp) ? resProp.GetString() : null;
        var preset = runConfigProp.TryGetProperty("Preset", out var presetProp) ? presetProp.GetString() : null;

        return new RunConfig(api, resolution, preset);
    }

    private static ChunkStats ComputeChunkStats(string chunksFolder)
    {
        if (!Directory.Exists(chunksFolder))
        {
            return ChunkStats.Empty;
        }

        var files = Directory.GetFiles(chunksFolder, "chunk_*.json");
        if (files.Length == 0)
        {
            return ChunkStats.Empty;
        }

        var stutter50 = 0;
        var stutter100 = 0;
        double worstFrameTime = 0;

        foreach (var file in files)
        {
            using var stream = File.OpenRead(file);
            var chunk = JsonSerializer.Deserialize<RawSampleChunk>(stream);
            if (chunk?.Samples is null)
            {
                continue;
            }

            foreach (var sample in chunk.Samples)
            {
                if (sample.FrameTimeMs >= 50)
                {
                    stutter50++;
                }

                if (sample.FrameTimeMs >= 100)
                {
                    stutter100++;
                }

                if (sample.FrameTimeMs > worstFrameTime)
                {
                    worstFrameTime = sample.FrameTimeMs;
                }
            }
        }

        return new ChunkStats(stutter50, stutter100, worstFrameTime);
    }

    private void BuildHeader(IContainer container, ReportData data)
    {
        container.Background(_theme.Primary).Padding(12).Row(row =>
        {
            row.RelativeItem().Column(column =>
            {
                column.Item().Text("ZykeMark Performance Report").FontSize(18).SemiBold();
                column.Item().Text($"Session: {data.SessionId}").FontSize(10);
                column.Item().Text($"Started: {data.StartedAtUtc:O}").FontSize(10);
                column.Item().Text($"Ended: {(data.EndedAtUtc.HasValue ? data.EndedAtUtc.Value.ToString("O") : "Not ended")}").FontSize(10);
            });

            row.ConstantItem(200).Column(column =>
            {
                if (!string.IsNullOrWhiteSpace(data.GameName))
                {
                    column.Item().AlignRight().Text(data.GameName).SemiBold();
                }

                if (!string.IsNullOrWhiteSpace(data.BuildVersion))
                {
                    column.Item().AlignRight().Text($"Build: {data.BuildVersion}");
                }
            });
        });
    }

    private void BuildContent(IContainer container, ReportData data, ReportInsights insights)
    {
        container.PaddingVertical(10).Column(column =>
        {
            column.Item().Element(section => BuildRunConfig(section, data));
            column.Item().Element(section => BuildKeyMetrics(section, data));
            column.Item().Element(section => BuildCpuGpu(section, data));
            column.Item().Element(section => BuildStability(section, data));
            column.Item().Element(section => BuildDataQuality(section, data, insights));
            column.Item().Element(section => BuildInterpretationNotes(section, insights));
            column.Item().Element(section => BuildNextSteps(section, data));
            column.Item().Element(section => BuildNextRunChecklist(section, data));
        });
    }

    private void BuildRunConfig(IContainer container, ReportData data)
    {
        container.Column(column =>
        {
            column.Item().Text("System & Run Config").FontSize(14).FontColor(_theme.Primary).SemiBold();
            column.Item().Text($"API: {ValueOrNotProvided(data.RunConfig.Api)}");
            column.Item().Text($"Resolution: {ValueOrNotProvided(data.RunConfig.Resolution)}");
            column.Item().Text($"Preset: {ValueOrNotProvided(data.RunConfig.Preset)}");

            var warnings = new List<string>();
            if (string.IsNullOrWhiteSpace(data.GameName)) warnings.Add("GameName");
            if (string.IsNullOrWhiteSpace(data.BuildVersion)) warnings.Add("BuildVersion");
            if (string.IsNullOrWhiteSpace(data.RunConfig.Api)) warnings.Add("API");
            if (string.IsNullOrWhiteSpace(data.RunConfig.Resolution)) warnings.Add("Resolution");
            if (string.IsNullOrWhiteSpace(data.RunConfig.Preset)) warnings.Add("Preset");

            if (warnings.Count > 0)
            {
                column.Item().PaddingTop(5).Background(_theme.Accent).Padding(6).Text(
                    $"Comparability warnings: Missing {string.Join(", ", warnings)}.");
            }
        });
    }

    private void BuildKeyMetrics(IContainer container, ReportData data)
    {
        container.Column(column =>
        {
            column.Item().PaddingTop(10).Text("Key Performance Metrics").FontSize(14).FontColor(_theme.Primary).SemiBold();
            column.Item().PaddingTop(6).Column(grid =>
            {
                grid.Item().Row(row =>
                {
                    row.RelativeItem().Element(card => BuildMetricCard(card, "Avg FPS", data.AvgFps.ToString("F1", CultureInfo.InvariantCulture)));
                    row.RelativeItem().Element(card => BuildMetricCard(card, "1% Low", data.OnePercentLowFps.ToString("F1", CultureInfo.InvariantCulture)));
                });
                grid.Item().Row(row =>
                {
                    row.RelativeItem().Element(card => BuildMetricCard(card, "0.1% Low", data.PointOnePercentLowFps.ToString("F1", CultureInfo.InvariantCulture)));
                    row.RelativeItem().Element(card => BuildMetricCard(card, "P99 Frame Time (ms)", data.P99FrameTimeMs.ToString("F2", CultureInfo.InvariantCulture)));
                });
                grid.Item().Row(row =>
                {
                    row.RelativeItem().Element(card => BuildMetricCard(card, "Avg Frame Time (ms)", data.AvgFrameTimeMs.ToString("F2", CultureInfo.InvariantCulture)));
                    row.RelativeItem().Element(card => BuildMetricCard(card, "Duration", FormatDuration(data.DurationMs)));
                });
            });
        });
    }

    private void BuildCpuGpu(IContainer container, ReportData data)
    {
        container.Column(column =>
        {
            column.Item().PaddingTop(10).Text("CPU vs GPU Balance").FontSize(14).FontColor(_theme.Primary).SemiBold();
            column.Item().Text($"Avg CPU Frame Time: {FormatNullableMs(data.AvgCpuFrameTimeMs)}");
            column.Item().Text($"Avg GPU Frame Time: {FormatNullableMs(data.AvgGpuFrameTimeMs)}");
            column.Item().Text($"Balance Hint: {GetBalanceHint(data.AvgCpuFrameTimeMs, data.AvgGpuFrameTimeMs)}");
        });
    }

    private void BuildStability(IContainer container, ReportData data)
    {
        container.Column(column =>
        {
            column.Item().PaddingTop(10).Text("Stability / Stutter").FontSize(14).FontColor(_theme.Primary).SemiBold();
            column.Item().Text($"P99 Frame Time: {data.P99FrameTimeMs.ToString("F2", CultureInfo.InvariantCulture)} ms");
            if (data.ChunkStats.HasData)
            {
                column.Item().Text($"Worst Frame Time: {data.ChunkStats.WorstFrameTimeMs.ToString("F2", CultureInfo.InvariantCulture)} ms");
                column.Item().Text($"Stutter Events >= 50ms: {data.ChunkStats.StutterEvents50Ms}");
                column.Item().Text($"Stutter Events >= 100ms: {data.ChunkStats.StutterEvents100Ms}");
            }
            else
            {
                column.Item().Text("No chunk data available for stutter analysis.");
            }
        });
    }

    private void BuildDataQuality(IContainer container, ReportData data, ReportInsights insights)
    {
        container.Column(column =>
        {
            column.Item().PaddingTop(10).Text("Data Quality & Context").FontSize(14).FontColor(_theme.Primary).SemiBold();

            if (insights.Flags.Count == 0)
            {
                column.Item().Text("No data-quality warnings detected for this run.");
                return;
            }

            foreach (var flag in insights.Flags)
            {
                column.Item().Background(_theme.Accent).Padding(6).Text($"{flag.Title}: {flag.Description}");
            }
        });
    }

    private void BuildInterpretationNotes(IContainer container, ReportInsights insights)
    {
        container.Column(column =>
        {
            column.Item().PaddingTop(10).Text("Interpretation Notes").FontSize(14).FontColor(_theme.Primary).SemiBold();
            column.Item().Text("1%/0.1% lows and worst-frame metrics can be distorted by focus loss, background activity, or overlays.");
            if (insights.DesktopCaptureLikely)
            {
                column.Item().Text("Desktop capture detected or likely. Prefer capturing the actual game process for actionable lows.");
            }
        });
    }

    private void BuildNextSteps(IContainer container, ReportData data)
    {
        container.Column(column =>
        {
            column.Item().PaddingTop(10).Text("Actionable Next Steps").FontSize(14).FontColor(_theme.Primary).SemiBold();
            var hint = GetBalanceHint(data.AvgCpuFrameTimeMs, data.AvgGpuFrameTimeMs);

            if (hint == "Likely CPU-bound")
            {
                column.Item().Text("• Profile main-thread hotspots and reduce simulation cost.");
                column.Item().Text("• Reduce draw calls/state changes and improve batching.");
                column.Item().Text("• Validate background tasks and thread contention.");
            }
            else if (hint == "Likely GPU-bound")
            {
                column.Item().Text("• Review shader complexity and post-processing passes.");
                column.Item().Text("• Evaluate resolution scaling or dynamic quality settings.");
                column.Item().Text("• Optimize texture/RT budget and overdraw.");
            }
            else
            {
                column.Item().Text("• Capture a longer run to reduce variance.");
                column.Item().Text("• Ensure fixed settings and consistent scene context.");
            }
        });
    }

    private void BuildNextRunChecklist(IContainer container, ReportData data)
    {
        var missing = new List<string>();
        if (string.IsNullOrWhiteSpace(data.GameName)) missing.Add("Game (e.g., MyGame)");
        if (string.IsNullOrWhiteSpace(data.BuildVersion)) missing.Add("Build (e.g., 1.0.0)");
        if (string.IsNullOrWhiteSpace(data.RunConfig.Api)) missing.Add("API (e.g., DX12)");
        if (string.IsNullOrWhiteSpace(data.RunConfig.Resolution)) missing.Add("Resolution (e.g., 1920x1080)");
        if (string.IsNullOrWhiteSpace(data.RunConfig.Preset)) missing.Add("Preset (e.g., High)");

        if (missing.Count == 0)
        {
            return;
        }

        container.Column(column =>
        {
            column.Item().PaddingTop(10).Text("Next-Run Checklist").FontSize(14).FontColor(_theme.Primary).SemiBold();
            foreach (var item in missing)
            {
                column.Item().Text($"• Provide {item}");
            }
        });
    }

    private static string ValueOrNotProvided(string? value) => string.IsNullOrWhiteSpace(value) ? "Not provided" : value;

    private static string FormatDuration(long? durationMs)
    {
        if (!durationMs.HasValue)
        {
            return "Not provided";
        }

        var seconds = durationMs.Value / 1000.0;
        return $"{seconds.ToString("F1", CultureInfo.InvariantCulture)} s";
    }

    private static string FormatNullableMs(double? value)
    {
        return value.HasValue
            ? $"{value.Value.ToString("F2", CultureInfo.InvariantCulture)} ms"
            : "Not provided";
    }

    private static string GetBalanceHint(double? cpuMs, double? gpuMs)
    {
        if (!cpuMs.HasValue || !gpuMs.HasValue)
        {
            return "Balanced / unclear";
        }

        if (cpuMs.Value > gpuMs.Value * 1.10)
        {
            return "Likely CPU-bound";
        }

        if (gpuMs.Value > cpuMs.Value * 1.10)
        {
            return "Likely GPU-bound";
        }

        return "Balanced / unclear";
    }

    private void BuildMetricCard(IContainer container, string title, string value)
    {
        container.Border(1).BorderColor(_theme.Primary).Padding(6).Column(column =>
        {
            column.Item().Text(title).FontSize(10).FontColor(_theme.Primary);
            column.Item().Text(value).FontSize(14).SemiBold();
        });
    }

    private static ReportInsights BuildInsights(ReportData data)
    {
        var flags = new List<InsightFlag>();

        if (data.FrameCount < 300)
        {
            flags.Add(new InsightFlag("Insufficient Sample Size", "Fewer than 300 frames captured; lows may be unstable."));
        }

        if (data.ChunkStats.WorstFrameTimeMs >= 1000)
        {
            flags.Add(new InsightFlag("High Outlier Risk", "Worst frame exceeded 1000 ms; verify focus and background load."));
        }

        if (data.ChunkStats.StutterEvents100Ms >= 20 || data.P99FrameTimeMs >= 100)
        {
            flags.Add(new InsightFlag("Severe Stutter", "High stutter frequency or elevated P99 frame time detected."));
        }

        var desktopCaptureLikely = !string.IsNullOrWhiteSpace(data.GameName)
            && data.GameName.Contains("Desktop", StringComparison.OrdinalIgnoreCase);

        if (desktopCaptureLikely)
        {
            flags.Add(new InsightFlag("Desktop Capture Likely", "Game name suggests a desktop capture rather than a game process."));
        }

        return new ReportInsights(flags, desktopCaptureLikely);
    }

    private sealed record ReportData(
        string SessionId,
        DateTime StartedAtUtc,
        DateTime? EndedAtUtc,
        long? DurationMs,
        string? GameName,
        string? BuildVersion,
        RunConfig RunConfig,
        double AvgFps,
        double OnePercentLowFps,
        double PointOnePercentLowFps,
        double AvgFrameTimeMs,
        double P99FrameTimeMs,
        int FrameCount,
        double? AvgCpuFrameTimeMs,
        double? AvgGpuFrameTimeMs,
        ChunkStats ChunkStats);

    private sealed record ChunkStats(int StutterEvents50Ms, int StutterEvents100Ms, double WorstFrameTimeMs)
    {
        public static ChunkStats Empty => new(0, 0, 0);
        public bool HasData => StutterEvents50Ms > 0 || StutterEvents100Ms > 0 || WorstFrameTimeMs > 0;
    }

    private sealed record ReportInsights(IReadOnlyList<InsightFlag> Flags, bool DesktopCaptureLikely);

    private sealed record InsightFlag(string Title, string Description);
}
